USE [ContosoRetailDW]
GO

CREATE VIEW [olap].[vProduct]
AS
	SELECT   [dp].[ProductKey]
			,[dp].[ProductLabel]
			,[dp].[ProductName]
			,[dp].[ProductDescription]
			,[dp].[ProductSubcategoryKey]
			,[dp].[Manufacturer]
			,[dp].[BrandName]
			,[dp].[ClassID]
			,[dp].[ClassName]
			,[dp].[StyleID]
			,[dp].[StyleName]
			,[dp].[ColorID]
			,[dp].[ColorName]
			,[dp].[Size]
			,[dp].[SizeRange]
			,[dp].[SizeUnitMeasureID]
			,[dp].[Weight]
			,[dp].[WeightUnitMeasureID]
			,[dp].[UnitOfMeasureID]
			,[dp].[UnitOfMeasureName]
			,[dp].[StockTypeID]
			,[dp].[StockTypeName]
			,[dp].[UnitCost]
			,[dp].[UnitPrice]
			,[dp].[AvailableForSaleDate]
			,[dp].[StopSaleDate]
			,[dp].[Status]
			,[dp].[ImageURL]
			,[dp].[ProductURL]
			,[dp].[ETLLoadID]
			,[dp].[LoadDate]
			,[dp].[UpdateDate]
			,[dpc].[ProductCategoryKey]
			,[dpc].[ProductCategoryLabel]
			,[dpc].[ProductCategoryName]
			,[dpc].[ProductCategoryDescription]
			,[dps].[ProductSubcategoryLabel]
			,[dps].[ProductSubcategoryName]
			,[dps].[ProductSubcategoryDescription]
	FROM [dbo].[DimProduct] AS dp
	INNER JOIN [dbo].[DimProductSubcategory] AS dps
		ON [dp].[ProductSubcategoryKey] = [dps].[ProductSubcategoryKey]
	INNER JOIN [dbo].[DimProductCategory] AS dpc
		ON [dps].[ProductCategoryKey] = [dpc].[ProductCategoryKey]
GO